package com.android.dazhihui;

/*import android.graphics.Bitmap;
import android.graphics.drawable.Drawable;
import android.webkit.WebView;*/
/*import com.android.dazhihui.ctrl.AlertTextCtrl;
import com.android.dazhihui.ctrl.FlashIndexTextView;
import com.android.dazhihui.ctrl.ProgressCtrl;
import com.android.dazhihui.ctrl.StockPondElement;*/
import java.util.Vector;

public class Globe
{
  public static int BottomButton_H;
  public static byte[] ByteArray;
  public static String ByteUrl;
  public static byte[] CashRanking_HotKeyId;
  public static String[] CashRanking_HotKeyTitle;
  public static boolean[] CashRanking_isHotkeyChecked;
  public static int GprsChoice;
  public static int MK_Height;
/*  public static Bitmap MainMenuBg_Down;
  public static Bitmap MainMenuBg_Down2;*/
  public static Vector<int[]> MainMenuIndex;
/*  public static Bitmap MainMenu_Bg;
  public static Bitmap MainMenu_Bg2;
  public static Bitmap[] Menu_Down;
  public static Bitmap[] Menu_Up;*/
  public static byte[] MessageBoxChoice;
  public static int MineStockSum;
  public static int SDK;
  public static int SMSMessageBoxChoice;
  public static int ServerChoice;
  public static boolean ShortCutChange;
  public static byte[] ShortCutChoice;
  public static int StockInfo_Index;
  public static int StockInfo_OldIndex;
  public static byte[] StockLater_HotKeyId;
  public static String[] StockLater_HotKeyTitle;
  public static boolean[] StockLater_isHotkeyChecked;
  public static byte[] StockMine_HotKeyId;
  public static String[] StockMine_HotKeyTitle;
  public static boolean[] StockMine_isHotkeyChecked;
  public static int StockPond_Table_Number;
/*  public static Bitmap SubMenuBg_Down;*/
  public static Vector<String[]> SubMenuName;
  public static Vector<String> SubMenuName2;
/*  public static Bitmap SubMenu_Bg;*/
  public static String[] TEXTVIEW_DATA;
  public static int TIME_BROWSER;
  public static int TIME_KLINE;
  public static int TIME_MINUTE;
  public static int TIME_RANK;
  public static int TIME_STOCK_MINE;
  public static int TableCell_H;
  public static int TableHead_H;
  public static int Table_Number;
  public static int Table_Number_;
  public static int Title_H;
/*  public static Vector<WindowsManager> ViewContainer;
  public static StockPondElement[] a_stockPond_f;*/
  public static String[][] accountTypes;
  public static int adImgID;
  public static int allCounter;
  public static String apn;
  public static int arg0;
  public static int arg1;
  public static int arg2;
  public static int arg3;
  public static Base base;
  public static int beginY;
  public static int beginY_mainmenubrowser;
  public static String bulletinWords;
  public static String businessType;
  public static boolean canShowFXJ;
  public static boolean canShowStockPond;
  public static int counter;
  public static int dataLength;
  public static long dataTime;
  public static int day;
  public static boolean debug ;
  public static String debugWords;
  public static String depart;
/*  public static Drawable drawable_Titlebg;
  public static Drawable drawable_gray;
  public static Drawable drawable_green;
  public static Drawable drawable_red;*/
  public static String[] entrustIP;
  public static int entrustIndex;
  public static int entrustNum;
  public static int firstView;
  public static int fullScreenHeight;
  public static int fullScreenWidth;
  public static int gameFontHeight;
  public static int gameFontHeight16;
  public static int gameFontHuge;
  public static int hasShownFirstWarn;
  public static int hasShownStockPondWarn;
  public static int hour;
  public static long httpKey;
/*  public static Bitmap img_AddStock;
  public static Bitmap img_Edit;
  public static Bitmap img_Landmine;
  public static Bitmap[] img_SubMenu2_Icon;
  public static Bitmap img_ad;
  public static Bitmap img_bPoint;
  public static Bitmap img_bxm_bg;
  public static Bitmap img_downArrow;
  public static Bitmap img_flipperbg;
  public static Bitmap img_jia;
  public static Bitmap img_jian;
  public static Bitmap img_leftArrow;
  public static Bitmap img_menuBg;
  public static Bitmap img_menuBg_down;
  public static Bitmap img_rightArrow;
  public static Bitmap img_sPoint;
  public static Bitmap img_subMenuSc;
  public static Bitmap img_upArrow;*/
  public static int infoAutoShow;
  public static boolean isChangeName;
  public static boolean isFlashIndex;
  public static boolean isInTrade;
  public static int isLoginAuto;
  public static int isMarkName;
  public static boolean isRefreshAlert;
  public static boolean isShownKlineTip;
  public static boolean isShownMinTip = true;
  public static boolean isShownWarnInMin;
  public static boolean isStockInfoShown;
  public static boolean isSwitcherShown;
  public static int isTableF10;
  public static int isVIP;
  public static byte[] key;
  public static long limits;
  public static String[] limitsString;
  public static int[] limitsTime;
/*  public static AlertTextCtrl m_AlertTextCtrl;
  public static FlashIndexTextView m_flashIndexTextViews;*/
  public static int maxFrames;
  public static int minute;
  public static int month;
  public static long newTime;
  public static long newTime_info;
  public static long newTime_phoneNumber;
  public static String newVision;
/*  public static Bitmap non_img;*/
  public static long oldTime;
  public static long oldTime_info;
  public static long oldTime_phoneNumber;
  public static long oldTime_send;
  public static String phoneNumber;
  public static String phoneType;
  public static String platform;
  public static int point;
  public static int port;
  public static String proxy;
  public static String qdh;
  public static int regionId;
  public static int saveScreenId;
  public static float scale_h;
  public static float scale_h2;
  public static float scale_icon;
  public static float scale_w;
  public static int second;
  public static String serHangIP;
  public static String serHangIP2;
  public static int serHangPort;
  public static int serTradePort;
  public static String setTradeIP;
  public static String setTradeIP2;
  public static String stockCode;
  public static String[] stockCodeArray;
  public static int stockCodeArrayIndex;
  public static String stockName;
  public static int stockPondFontBig;
  public static int stockPondFontMini;
  public static int stockPondFontNormal;
  public static int stockPondFontSmall;
  public static int stockpond_wId;
  public static String str_stockpond_warning;
  public static int subMenuFontWidth;
  public static String systemId;
  public static int titleFontWidth;
  public static int titlebarH;
  public static long tradeoldTime;
  public static String[] traderName;
  public static String updateUrl;
  public static String userId;
  public static String userName;
  public static String userPassWord;
  public static String userRanId;
  public static Vector<String> vecFreeStock;
  public static Vector<String> vecLaterStock;
  public static int wap;
  public static int warningId;
/*  public static WebView webView;*/
  public static int year;
/*  public static Bitmap zjlxBg2_Down;
  public static Bitmap zjlxBg_Down;
  public static Bitmap zjlx_Bg;
  public static Bitmap zjlx_Bg2;*/

  static
  {
    isShownKlineTip = true;
    isStockInfoShown = false;
    StockInfo_Index = 0;
    StockInfo_OldIndex = 0;
    phoneType = "";
    apn = "";
    proxy = null;
    port = 0;
    isVIP = 0;
    isMarkName = 0;
    isLoginAuto = 0;
    firstView = 0;
    infoAutoShow = 0;
    allCounter = 0;
    //public static final String[] STOCK_TYPE_HAD_STR = { "SZ", "SH", "BI", "SC", "DC", "ZC", "SF" };
    //public static final String[] HTTP_SERVER = { "222.73.34.8:12346", "222.73.103.42:12346", "61.151.252.4:12346", "61.151.252.14:12346" };
    serHangIP = "114.80.158.20";              //"114.80.158.20:12345"(log); //222.73.103.52:12345(DAZHIHUI.db)
    serHangIP2 ="114.80.158.20";           // "114.80.158.20"; //222.73.103.52
    serHangPort = 12345;//12345;
    phoneNumber = "";
    userId = "";
    userName = "";
    userPassWord = "";
    userRanId = "";
    adImgID = 0;
    bulletinWords = null;
    newVision = "";
    updateUrl = "";
    httpKey = 0L;
    limits = 0L;
    limitsTime = null;
    limitsString = new String[14];
    warningId = 0;
    stockpond_wId = 0;
    systemId = "";
    oldTime = 0L;
    newTime = 0L;
    oldTime_phoneNumber = 0L;
    newTime_phoneNumber = 0L;
    oldTime_info = 0L;
    newTime_info = 0L;
    oldTime_send = 0L;
    GprsChoice = 0;
    ServerChoice = 0;
    MessageBoxChoice = null;
    SMSMessageBoxChoice = 1;
    ShortCutChange = false;
    platform = "Gphone";
    qdh = "";
    fullScreenWidth = 0;
    fullScreenHeight = 0;
    wap = 1;
    vecFreeStock = new Vector();
    vecLaterStock = new Vector();
    maxFrames = 10;
    TIME_BROWSER = 80;
    TIME_STOCK_MINE = 15;
    TIME_MINUTE = 5;
    TIME_KLINE = 15;
    TIME_RANK = 15;
    beginY_mainmenubrowser = 0;
    beginY = 0;
    titlebarH = 0;
    BottomButton_H = 0;
    Title_H = 0;
    TableHead_H = 0;
    TableCell_H = 0;
 /*   non_img = null;
    img_flipperbg = null;
    img_ad = null;
    img_jia = null;
    img_jian = null;
    MainMenu_Bg = null;
    SubMenu_Bg = null;
    MainMenuBg_Down = null;
    SubMenuBg_Down = null;
    MainMenu_Bg2 = null;
    MainMenuBg_Down2 = null;
    zjlx_Bg = null;
    zjlxBg_Down = null;
    zjlx_Bg2 = null;
    zjlxBg2_Down = null;
    Menu_Up = null;
    Menu_Down = null;
    img_bPoint = null;
    img_sPoint = null;
    img_subMenuSc = null;
    img_AddStock = null;
    img_Edit = null;
    img_Landmine = null;
    img_upArrow = null;
    img_downArrow = null;
    img_bxm_bg = null;
    img_leftArrow = null;
    img_rightArrow = null;
    img_menuBg = null;
    img_menuBg_down = null;*/
    gameFontHeight = 20;
    gameFontHeight16 = 0;
    subMenuFontWidth = 0;
    titleFontWidth = 0;
    stockPondFontBig = 0;
    stockPondFontSmall = 0;
    stockPondFontNormal = 0;
    stockPondFontMini = 0;
    gameFontHuge = 0;
    stockCode = "";
    stockName = "";
    regionId = 0;
    stockCodeArray = null;
    stockCodeArrayIndex = 0;
    canShowStockPond = false;
    canShowFXJ = false;
    point = 0;
    key = null;
/*    webView = null;*/
/*    progressCtrl = null;*/
    debug = true;
    dataTime = 0L;
    dataLength = 0;
    debugWords = "";
    ByteArray = null;
    ByteUrl = null;
    Table_Number = 20;
    Table_Number_ = 20;
    isSwitcherShown = false;
    MainMenuIndex = new Vector();
    SubMenuName = new Vector();
    SubMenuName2 = new Vector();
    str_stockpond_warning = "";
    CashRanking_HotKeyTitle = null;
    CashRanking_isHotkeyChecked = null;
    CashRanking_HotKeyId = null;
    StockLater_HotKeyTitle = null;
    StockLater_isHotkeyChecked = null;
    StockLater_HotKeyId = null;
    StockMine_HotKeyTitle = null;
    StockMine_isHotkeyChecked = null;
    StockMine_HotKeyId = null;
    hasShownFirstWarn = 0;
    hasShownStockPondWarn = 0;
    isShownWarnInMin = false;
    isTableF10 = 0;
    MineStockSum = 0;
    setTradeIP = "";
    setTradeIP2 = "";
    isInTrade = true;
    businessType = null;
    depart = null;
    entrustIndex = -1;
    entrustNum = 14;
    traderName = new String[] { "����֤ȯ", "�°�֤ȯ", "��ʱ��֤ȯ", "��ʱ��Զ��֤ȯ", "����֤ȯ", "�ڳ�֤ȯ", "����֤ȯ", "��ɽ֤ȯ", "����֤ȯ", "��̩��֤ȯ", "����֤ȯ", "����֤ȯ", "���֤ȯ", "��Դ֤ȯ" };
    entrustIP = new String[] { "116.228.234.72:8843", "222.73.18.205:8843", "60.247.4.34:8843", "222.68.172.70:8843", "114.80.111.105:8843", "113.128.248.254:8843", "222.68.178.238:8843", "58.251.38.45:8843", "124.74.201.220:8843", "210.13.95.78:8843", "222.66.167.209:8843", "218.5.69.35:8843", "219.134.241.196:8843", "219.143.219.239:8843" };
    tradeoldTime = 0L;
  }
}

/* Location:           D:\android\Git\dzh_585\dzh_585\libs\dazhihui_5_85_dex2jar.jar
 * Qualified Name:     com.android.dazhihui.Globe
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.5.3
 */